# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='md5',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='original',
            field=models.FileField(blank=True, null=True, upload_to='legistar'),
        ),
    ]
