# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 06:47
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20161111_0119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_updated', models.DateTimeField(auto_now=True, db_index=True, help_text='The datetime this actual object was updated.', null=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The datetime this actual object was created.', null=True)),
                ('title', models.CharField(blank=True, db_index=True, max_length=256, null=True)),
                ('kind', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('source_url', models.TextField(blank=True, null=True)),
                ('json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('slug', models.CharField(db_index=True, max_length=1024)),
            ],
            options={
                'get_latest_by': '-datetime_updated',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_updated', models.DateTimeField(auto_now=True, db_index=True, help_text='The datetime this actual object was updated.', null=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The datetime this actual object was created.', null=True)),
                ('title', models.CharField(blank=True, db_index=True, max_length=256, null=True)),
                ('kind', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('source_url', models.TextField(blank=True, null=True)),
                ('json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('guid', models.CharField(db_index=True, max_length=64)),
                ('location', models.TextField(blank=True, null=True)),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='core.Body')),
            ],
            options={
                'get_latest_by': '-datetime_updated',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='document',
            name='meeting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.Body'),
        ),
    ]
