# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 06:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20161111_0647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='body',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='meeting',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='body',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='document',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='kind',
        ),
    ]
