# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20161111_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='time',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
