# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 05:53
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20161112_0556'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('datetime_updated', models.DateTimeField(auto_now=True, db_index=True, help_text='The datetime this actual object was updated.', null=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The datetime this actual object was created.', null=True)),
                ('source_url', models.TextField(blank=True, null=True)),
                ('json', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('number', models.IntegerField(db_index=True)),
                ('type', models.CharField(blank=True, db_index=True, max_length=256, null=True)),
            ],
            options={
                'get_latest_by': '-datetime_updated',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='document',
            name='agenda_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.AgendaItem'),
        ),
    ]
