# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_agendaitem_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaitem',
            name='version',
            field=models.IntegerField(db_index=True, default=1),
            preserve_default=False,
        ),
    ]
