# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_agendaitem_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendaitem',
            name='number',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
